name: Release OTA Firmware

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    env:
      BUILD_DIR: build
      PROJECT_NAME: Project1
      RELEASE_DIR: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          VERSION="${GITHUB_REF_NAME}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Using version: $VERSION"

      - name: Build firmware with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.3
          target: esp32s3
          path: '.'
          command: |
            idf.py -D PROJECT_VER=${{ steps.version.outputs.version }} build

      - name: Prepare release folder
        run: mkdir -p "${RELEASE_DIR}"

      - name: Copy firmware into release folder
        run: |
          cp "${BUILD_DIR}/${PROJECT_NAME}.bin" \
             "${RELEASE_DIR}/firmware-${{ steps.version.outputs.version }}.bin"

      - name: Generate s3_manifest.json
        run: |
          cat > "${RELEASE_DIR}/s3_manifest.json" <<EOF
          {
            "version": "${{ steps.version.outputs.version }}",
            "firmware_url": "https://192.168.3.125:4443/firmware-${{ steps.version.outputs.version }}.bin",
            "target": "esp32s3",
            "flash_size_MB": "16",
            "commit_version" : "${{ github.sha }}"
          }
          EOF

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ota-release-${{ steps.version.outputs.version }}
          path: |
            release/firmware-${{ steps.version.outputs.version }}.bin
            release/s3_manifest.json